<?php

namespace IotaDigital\LaravelApiVersioning\Console\Commands;

use Illuminate\Foundation\Console\RouteListCommand;

class RouteList extends RouteListCommand
{
    protected $name = 'route:list {version?}';

    protected function getRoutes()
    {
        return parent::getRoutes(); // TODO: Change the autogenerated stub
    }
}
